version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-interaction
    - python -m sphinx -b html docs/ $READTHEDOCS_OUTPUT/html
