# @package _global_

defaults:
  - _self_

# Training parameters
run:
  seed: 0
  num_envs: 1
  steps_per_env: 50000
  eval_frequency: 5000
  eval_rollouts: 50
  eval_episode_save_frequency: 5000
  eval_episode_save_count: 1

env:
  name: cartpole-control

# Agent overrides
agent:
  name: dqn
  epsilon_decay_fraction: 0.4
  target_network_frequency: 100

# W&B settings
wandb:
  enabled: false
